name: spirit-box-client
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ffmpeg=7.0
  - pip:
      - python-dotenv==1.0.1
      - click==8.1.7
      - sounddevice==0.5.0
      - numpy==2.1.1
      - pynput==1.7.7
      - pydub==0.25.1
      - requests==2.32.3
      - pygame==2.6.0
