name: spirit-box-server
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=21
  - ffmpeg<7
  - pip:
      - python-dotenv==1.0.1
      - click==8.1.7
      # bark
      - audiolm-pytorch==1.1.4
      - fairseq
      - huggingface-hub
      - sentencepiece
      - transformers
      - encodec
      - soundfile; platform_system == "Windows"
      - sox; platform_system != "Windows"
      - git+https://github.com/serp-ai/bark-with-voice-clone.git
      # whisper
      - openai-whisper==20231117
