name: spirit-box
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pip:
      - python-dotenv==1.0.1
      - click==8.1.7
      - nltk==3.9.1
      # bark & text generation
      - huggingface-hub
      - transformers
      - encodec
      - pydub==0.25.1
      # whisper
      - openai-whisper==20231117
      # socketio
      - python-socketio==5.11.4
      - eventlet==0.36.1
