name: spirit-box-server
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip=21
  - conda-forge::ffmpeg<7
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip:
      - python-dotenv==1.0.1
      - click==8.1.7
      # bark
      - audiolm-pytorch==1.1.4
      - fairseq
      - huggingface-hub
      - sentencepiece
      - transformers
      - encodec
      - soundfile; platform_system == "Windows"
      - sox; platform_system != "Windows"
      - git+https://github.com/serp-ai/bark-with-voice-clone.git
      # whisper
      - openai-whisper==20231117
      - pydub==0.25.1
      # flask
      - flask==3.0.3
      - eventlet==0.36.1
      - greenlet==3.0.3
