name: spirit-box
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=21
  - ffmpeg<7
  - pip:
      - audiolm-pytorch==1.1.4
      - fairseq
      - huggingface-hub
      - sentencepiece
      - transformers
      - encodec
      - soundfile; platform_system == "Windows"
      - sox; platform_system != "Windows"
      - git+https://github.com/serp-ai/bark-with-voice-clone.git
